In [1]:
import numpy as np

from scipy.stats import pearsonr

alice = np.array([5, 3, 4, 4])
user1 = np.array([3, 1, 2, 3])
user2 = np.array([4, 3, 4, 3])
user3 = np.array([1, 5, 5, 2])

corr = pearsonr(alice, user1)

print(corr)

PearsonRResult(statistic=np.float64(0.8528028654224415), pvalue=np.float64(0.14719713457755845))


In [2]:
matrix = np.array([[5, 3, 4, 4],
                   [3, 1, 2, 3],
                   [4, 3, 4, 3],
                   [3, 3, 1, 5],
                   [1, 5, 5, 2]
                  ])

corr = np.corrcoef(matrix)

print(corr)

[[ 1.          0.85280287  0.70710678  0.         -0.79211803]
 [ 0.85280287  1.          0.30151134  0.42640143 -0.88662069]
 [ 0.70710678  0.30151134  1.         -0.70710678 -0.14002801]
 [ 0.          0.42640143 -0.70710678  1.         -0.59408853]
 [-0.79211803 -0.88662069 -0.14002801 -0.59408853  1.        ]]


In [6]:
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')

alice = np.array([5, 3, 4, 4])
user1 = np.array([3, 1, 2, 3])
user2 = np.array([4, 3, 4, 3])
user3 = np.array([3, 3, 1, 5])
user4 = np.array([1, 5, 5, 2])

plt.scatter(alice, user1)
plt.show()